FROM <%= @base_image_name %>:<%= @base_image_tag %>

ENV CHEF_NODE_NAME <%= @build_node_name %>
<% @dockerfile_commands.each do |d| %>
<%= d %>
<% end %>
ADD chef/ /etc/chef/
RUN chef-init --bootstrap
RUN rm /etc/chef/secure/validation.pem /etc/chef/secure/encrypted_data_bag_secret
ENTRYPOINT ["chef-init"]
CMD ["--onboot"]
