FROM <%= @base_image_name %>:<%= @base_image_tag %>

ENV CHEF_NODE_NAME <%= @build_node_name %>
<% @dockerfile_commands.each do |d| %>
<%= d %>
<% end %>
ADD chef/ /etc/chef/
RUN chef-init -z --bootstrap
RUN rm -rf /etc/chef/secure/*
ENTRYPOINT ["chef-init"]
CMD ["-z", "--onboot"]
